### ISSUE TITLE
0.3 version not on Maven central 

### ISSUE THREAD

**Issue by soumyasd** [mp911de/spinach#22]
We want to use the QueueListener API which is released in 0.3 according to https://github.com/mp911de/spinach/blob/0dea83ec3b7c4c6ab13efc299d8f8e4ea2d8a8ef/RELEASE-NOTES.md. 

However, this is not on Maven central. Any idea when 0.3 will be available ? 

Thanks.

**Comment by mp911de** [comment]
I'm planning to release spinach 0.3 end of January. spinach 0.3 is available as snapshot-build (0.3-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots/, see also https://oss.sonatype.org/content/repositories/snapshots/biz/paluch/redis/spinach/0.3-SNAPSHOT/). I'm spinach 0.3 requires lettuce 3.4 and lettuce 3.4 will be released also end of January .

**Comment by mp911de** [comment]
Released 0.3 to Maven central
