### ISSUE TITLE
Counters not being parsed when retrieving multiple Jobs.

### ISSUE THREAD

**Issue by jasxir** [mp911de/spinach#24]
While trying to get the job with counters
`public Map<String, Long> biz.paluch.spinach.api.Job<K, V>.getCounters();`
this method is giving an empty map.

Though while monitoring the disque port I'm able to see that Information

Request sent.

```
GETJOB
$7
TIMEOUT
$4
3000
$5
COUNT
$1
2
$12
WITHCOUNTERS
$4
FROM
$12
queue1
```

Response received.

```
D-c2febd4b-JS81tdlqarcPjxLnZ9eLi9bQ-003d
$57
job-body
$5
nacks
:74
$21
additional-deliveries
:1
:1
:1
*1
*7
$12
queue1
```

**Comment by mp911de** [comment]
Thanks for the bug report. Fixed with 4252580.

**Comment by jasxir** [comment]
Thank for the prompt fix.

**Comment by jasxir** [comment]
Thanks for the prompt fix.
